<a href="https://colab.research.google.com/github/Praveenku32k/Generative_Ai/blob/main/Text_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [13]:
data=pd.DataFrame({"text":["people watch ineuorn","ineuorn watch ineuorn","people write comment","ineuorn write comment"],"output":[1,1,0,0]})

In [5]:
!pip install scikit-learn

#BOW

In [14]:
Mfrom sklearn.feature_extraction.text import CountVectorizer

In [15]:
BOW=CountVectorizer()

In [16]:
document_matrix=BOW.fit_transform(data["text"])

In [17]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [18]:
BOW.vocabulary_

{'people': 2, 'watch': 3, 'ineuorn': 1, 'write': 4, 'comment': 0}

In [20]:
document_matrix[0]

<1x5 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [21]:
document_matrix[0].toarray() # we are converting into numpy.

array([[0, 1, 1, 1, 0]])

In [22]:
document_matrix[1].toarray() # we are converting into numpy.

array([[0, 2, 0, 1, 0]])

# Bigram

In [28]:
bigram=CountVectorizer(ngram_range=(2,2))

In [29]:
bigramvocab=bigram.fit_transform(data["text"])

In [31]:
bigram.vocabulary_

{'people watch': 2,
 'watch ineuorn': 4,
 'ineuorn watch': 0,
 'people write': 3,
 'write comment': 5,
 'ineuorn write': 1}

# Trigram

In [32]:
trigram=CountVectorizer(ngram_range=(3,3))

In [33]:
trigramvocab=trigram.fit_transform(data["text"])

In [34]:
trigram.vocabulary_

{'people watch ineuorn': 2,
 'ineuorn watch ineuorn': 0,
 'people write comment': 3,
 'ineuorn write comment': 1}

In [35]:
mix=CountVectorizer(ngram_range=(1,2))

In [36]:
mix_vocab=mix.fit_transform(data["text"])

In [38]:
mix.vocabulary_


{'people': 4,
 'watch': 7,
 'ineuorn': 1,
 'people watch': 5,
 'watch ineuorn': 8,
 'ineuorn watch': 2,
 'write': 9,
 'comment': 0,
 'people write': 6,
 'write comment': 10,
 'ineuorn write': 3}

#TFIDF

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [40]:
tfidf=TfidfVectorizer()

In [44]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [47]:
tfidf.get_feature_names_out() # here they are arraing in alphabetical order

array(['comment', 'ineuorn', 'people', 'watch', 'write'], dtype=object)

In [49]:
tfidf.idf_ # this my idf value,of each documents.

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])